### ISSUE TITLE
How to download the pretrained_models/82.6_T2T_ViTt_24.pth.tar ?

### ISSUE THREAD

**Issue by cuge1995** [Muzammal-Naseer/Improving-Adversarial-Transferability-of-Vision-Transformers#1]

**Comment by Muzammal-Naseer** [comment]
Hi,

Please use the token-to-token repo to download their models.

Here is the link :) : [https://github.com/yitu-opensource/T2T-ViT](https://github.com/yitu-opensource/T2T-ViT)
